// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenManhDuc392.Migrations
{
    [DbContext(typeof(NguyenManhDucDBContext))]
    [Migration("20211217082657_Table_NMD392")]
    partial class Table_NMD392
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("NguyenManhDuc392.Models.NMD392", b =>
                {
                    b.Property<string>("NMDID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NMDGende")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NMDName")
                        .HasColumnType("TEXT");

                    b.HasKey("NMDID");

                    b.ToTable("NMD392");
                });

            modelBuilder.Entity("NguyenManhDuc392.Models.UniversityNMD392", b =>
                {
                    b.Property<string>("UniversityID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityID");

                    b.ToTable("UniversityNMD392");
                });
#pragma warning restore 612, 618
        }
    }
}
