// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenManhDuc392.Migrations
{
    [DbContext(typeof(NguyenManhDucDBContext))]
    partial class NguyenManhDucDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("NguyenManhDuc392.Models.UniversityNMD392", b =>
                {
                    b.Property<string>("UniversityID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityID");

                    b.ToTable("UniversityNMD392");
                });
#pragma warning restore 612, 618
        }
    }
}
